on:
  push:
    branches:
      - main

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: Deploy this project to OpenFn/Lightning
    steps:
      - name: Deploy to Lightning
        uses: openfn/deploy-action@v0.1.9 
        with: 
          secret_input: ${{ secrets.OPENFN_API_KEY }}
